### ISSUE TITLE
Exit code -1073740791 when run mi test app in IIS Server 10

### ISSUE THREAD

**Issue by DoncoMsk** [smartinmedia/Net-Core-DocX-HTML-To-PDF-Converter#14]
Everything works fine under IISExpress or Console application. When I try to run under IIS server, it doesn't work.

I am running under DefaultAppPool and I have given permission to DefaultAppPool to access LibreOffice directory but I am not able to get result.

**Comment by Nikolilol** [comment]
hi @DoncoMsk,

I got the same issue with you, would you help to guide how did you fix this?
Thank you.

**Comment by scharez** [comment]
Hey, 

I also got the same problem? Did you already fix this?

thanks a lot.

**Comment by cturner-pulsion** [comment]
https://github.com/smartinmedia/Net-Core-DocX-HTML-To-PDF-Converter/issues/19#issuecomment-1327342579
